import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Head from 'next/head'

import { AllProviders } from '@/providers'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const shouldIndexContent = process.env.NEXT_PUBLIC_ROBOTS_INDEX === 'true'

  const env = process.env.NODE_ENV

  return (
    <html lang="pt-BR" className={`w-full`}>
      <Head>
        {env === 'development' || env === 'test' || (env === 'production' && shouldIndexContent)}
        <meta name="robots" content="noindex, nofollow, noarchive, nosnippet" />
        <meta name="googlebot" content="noindex, nofollow" />
      </Head>
      <body className={`w-full ${inter.className}`}>
        <AllProviders>{children}</AllProviders>
      </body>
    </html>
  )
}
