import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={`w-full h-full overflow-hidden`}>
      <body className={`w-full h-full overflow-hidden ${inter.className}`}>
        <div className="w-full h-full bg-brand-grey-000 overflow-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
